version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Run tests
          command: echo 'TEsting !!!!' 

workflows:
  example:
    jobs:
      - test
